name:                env
version:             0.1.0.0
github:              "lucas-miranda/wm-config"
author:              "Lucas A Miranda"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/env#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
